/**
 * Names this node, and its version, in Shotstack's render log.
 *
 * Every request must send it. n8n replaces a missing User-Agent with a bare
 * "n8n", which is what a plain HTTP Request node sends, so the render becomes
 * uncountable.
 *
 * GENERATED by scripts/build-user-agent.mjs. Do not edit.
 */
export const USER_AGENT = 'shotstack-n8n-node/0.1.0';
